export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "NoSQL"
  | "Framer Motion"
  | "Python"
  | "Bash"
  | "Gemini API"
  | "LM Studio"
  | "JSON"
  | "jq"
  | "YOLO"
  | "Python"
  | "Swift"
  | "iOS"
  | "Android"
  | "Computer Vision"
  | "Edge AI";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling"
  | "Developer Tools"
  | "Automation"
  | "Generative AI"
  | "AI"
  | "SportsTech"
  | "Sports Tech"
  | "Computer Vision";

export type ValidExpType = "Personal" | "Professional";

export type ValidPages =
  | "home"
  | "projects"
  | "contact"
  | "blog";
